name: Generate docs
on:
  release:
    types: [published]
  workflow_call:
permissions:
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Restore cached benchmark data
        uses: actions/cache/restore@v4
        with:
          key: ${{ runner.os }}-benchmark-${{ github.run_id }}
          path: ./cache
          restore-keys: |
            ${{ runner.os }}-benchmark-

      - run: |
          pnpm install --no-frozen-lockfile
          pnpm build:examples
          pnpm run docs
          cp -r ./cache/* ./docs
          mkdir -p ./docs/examples
          cp -r ./examples/chat/dist ./docs/examples/chat
          cp -r ./examples/grid/dist ./docs/examples/grid
          cp -r ./examples/canvas/dist ./docs/examples/canvas
          cp -r ./examples/local-bootstrap/dist ./docs/examples/local-bootstrap
          find ./docs/examples -type f -name 'index.html' -exec sed -i 's|src="/assets/|src="assets/|g' {} +
          find ./docs/examples -type f -name 'index.html' -exec sed -i 's|href="/assets/|href="assets/|g' {} +
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
